/*
-- Query: SELECT * FROM bearcathub.furniture
LIMIT 0, 50000

-- Date: 2023-10-03 17:46
*//*
-- Query: SELECT * FROM bearcathub.users
-- Date: 2023-10-03 17:16
*/
INSERT INTO users(`id`,`email`,`password`,`first_name`,`last_name`) VALUES (1,'s555620@nwmissouri.edu','root','Mamatha','Mallela');
INSERT INTO users(`id`,`email`,`password`,`first_name`,`last_name`) VALUES (2,'s555619@nwmissouri.edu','root','Gautam','Sagar');

INSERT INTO bearcathub.furniture(`id`,`name`,`furniture_condition`,`years_used`,`image_url`,`furniture_type`,`furniture_description`,`Donated_date`,`user_id`,`status`) VALUES (101,'Classic Wooden Chair','Good',1,'https://images.pexels.com/photos/3705539/pexels-photo-3705539.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1','Chair','This is a classic wooden corner chair with good condition. Its sturdy wooden frame exhibits a rich, lustrous finish, with no noticeable scratches or dents. The plush seat and backrest cushions remain firm and comfortable, showing no sagging or deformation.','2023-10-09 00:00:00',1,'available');
INSERT INTO bearcathub.furniture(`id`,`name`,`furniture_condition`,`years_used`,`image_url`,`furniture_type`,`furniture_description`,`Donated_date`,`user_id`,`status`) VALUES (102,'Outdoor Wooden Table','Excellent',1,'https://images.pexels.com/photos/14656123/pexels-photo-14656123.jpeg?auto=compress&cs=tinysrgb&w=600','Table','This Outdoor Wooden Table with Chairs is in excellent condition. The edges are smooth, with no chipping or dents, ensuring a professional and neat appearance. All adjustable components, such as the height and drawer mechanisms, work smoothly and without any hitches.','2023-11-09 00:00:00',2,'available');
INSERT INTO bearcathub.furniture(`id`,`name`,`furniture_condition`,`years_used`,`image_url`,`furniture_type`,`furniture_description`,`Donated_date`,`user_id`,`status`) VALUES (103,'Modern Lounge Chair','Excellent',1,'https://images.pexels.com/photos/6198655/pexels-photo-6198655.jpeg?auto=compress&cs=tinysrgb&w=600','Chair','This Modern Leather Lounge Chair is in excellent condition. Its sturdy wooden frame exhibits a rich, lustrous finish, with no noticeable scratches or dents.','2023-02-09 00:00:00',1,'available');
INSERT INTO bearcathub.furniture(`id`,`name`,`furniture_condition`,`years_used`,`image_url`,`furniture_type`,`furniture_description`,`Donated_date`,`user_id`,`status`) VALUES (104,'L Shaped Modular Sofa','Good',2,'https://media.istockphoto.com/id/1400158791/photo/living-room.jpg?b=1&s=612x612&w=0&k=20&c=vw2gE5tifx5IohnXSMlg6VFerY3I20kzUN6j7mzKvs4=','Sofa','This L Shaped Modular Sofa Set is in good condition, showing minimal signs of wear and tear. Its upholstery, a rich velvet fabric remains free from any noticeable stains, tears, or fading. The cushions are still firm and comfortable, providing ample support.','2023-10-09 00:00:00',1,'available');
INSERT INTO bearcathub.furniture(`id`,`name`,`furniture_condition`,`years_used`,`image_url`,`furniture_type`,`furniture_description`,`Donated_date`,`user_id`,`status`) VALUES (105,'Three Seater Sofa','Excellent',2,'https://images.pexels.com/photos/4857775/pexels-photo-4857775.jpeg?auto=compress&cs=tinysrgb&w=600','Sofa','This three Seater Sofa is in excellent condition. The wooden frame and legs are sturdy and intact, with no visible scratches or chips. Overall, this sofa appears almost brand new, well-cared-for, and ready to provide years of comfort and style to any living space.','2023-04-09 00:00:00',1,'available');
INSERT INTO bearcathub.furniture(`id`,`name`,`furniture_condition`,`years_used`,`image_url`,`furniture_type`,`furniture_description`,`Donated_date`,`user_id`,`status`) VALUES (106,'White Computer Desk','Good',1,'https://images.pexels.com/photos/5998739/pexels-photo-5998739.jpeg?auto=compress&cs=tinysrgb&w=600','Table','This White Computer or Laptop Desk is in good condition. Its sleek, polished wooden surface remains free from scratches, stains, or blemishes. The edges are smooth, with no chipping or dents, ensuring a professional and neat appearance. The metal legs and framework are sturdy and rust-free, providing stability and durability.','2023-10-09 00:00:00',1,'available');
INSERT INTO bearcathub.furniture(`id`,`name`,`furniture_condition`,`years_used`,`image_url`,`furniture_type`,`furniture_description`,`Donated_date`,`user_id`,`status`) VALUES (107,'Adjustable Study Lamp','Good',3,'https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&w=600',@@@
